# Generated by Django 4.2.23 on 2025-07-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dareupload_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DareExchange',
        ),
    ]
